### ISSUE TITLE
Update Indonesian-Language

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/SemPress#22]
@tigefa4u I added some new fields... do you have some time to update the Indonesian translation? I updated the files, you only have to add the missing translations.

**Comment by rilut** [comment]
d4f72e0 - translated the missing fields in id_ID.po and fixed some previous translations

**Comment by tigefa4u** [comment]
fixed?

**Comment by rilut** [comment]
Fixed.

**Comment by pfefferle** [comment]
Fixed :)
