### ISSUE TITLE
hcard class is unnecessary? 

### ISSUE THREAD

**Issue by ihorzenich** [pfefferle/SemPress#36]
There is class `hcard` in your theme, but I can't find that class in Microformats wiki (they have `h-card` and `vcard` which you already set) . Is it a mistake? Should you remove it?

**Comment by pfefferle** [comment]
It is not really a mistake, I added it to be more consistent with h-card. But at the end it is only a CSS-class and does not break anything, so there is no need to remove it, I think ;)

**Comment by ihorzenich** [comment]
But your theme is microformats/microdata based, users expect to see there only microformats/microdata classes. „hcard“ name confuses. What means „be more consistent with h-card“?
