### ISSUE TITLE
rel-feed support for Bridgy and Instagram

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/SemPress#40]
While I'm thinking about Bridgy/Instagram support and mf2, I thought I'd cross post this issue https://github.com/snarfed/bridgy/issues/671#issuecomment-219580229 here as it doesn't look like SemPress supports this out of the box.

**Comment by pfefferle** [comment]
SemPress is using `h-feed` on the front-page and `h-entry` on the front- and single-pages, so I think it should support it out of the box. @snarfed Is there a testparser for bridgy, to test for correct markup?

**Comment by snarfed** [comment]
sure! you'd just sign up, hit the Crawl Now button, then look at the log and check that it found your feed and posts. not a dedicated validator, but it works.

there are definitely plenty of bridgy users on sempress, so it should work as is.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/SemPress/issues/40#issuecomment-219651108" class="u-in-reply-to"></a>I'd tested SemPress last night and didn't see anything immediately.  Apparently I was only missing... patience (and maybe a cache flush). It does appear to work properly for this use-case. Apologies.
