### ISSUE TITLE
sempress_pre_get_avatar_data array errors

### ISSUE THREAD

**Issue by mtomas7** [pfefferle/SemPress#43]
Good day!

one user reported to me that:

PHP Warning: array_unique() expects parameter 1 to be array, null given
in /inc/semantics.php

Pointing to the line with sempress_pre_get_avatar_data function.

Thank you!

**Comment by pfefferle** [comment]
I can't find any issues in the code... What version of SemPress has the user installed?

This code should prevent that `$args['class']` can't be `null`:

```PHP
if ( ! isset( $args['class'] ) ) {
	$args['class'] = array();
}
```

**Comment by mtomas7** [comment]
He's using my theme Tiny Framework, but that particular function I'm using from your theme is identical, that's why I thought you would like to know about it.

Is it possible that it is related to some MySQL and PHP versions?
