### ISSUE TITLE
Limit categories on home page?

### ISSUE THREAD

**Issue by scottjenson** [pfefferle/SemPress#47]
I have 3 categories of articles on my blog but I only want one to show on the home page. It isn't clear how to do this w/ SemPress. Is this somehow built into the theme and I'm just missing it? Or is there a simple way to tweak the code to get this to happen?

Thanks! Scott

**Comment by scottjenson** [comment]
I'm currently using this php which works. Just wanted to know if this was overkill.

<?php
add_action('pre_get_posts', 'ad_filter_categories');
function ad_filter_categories($query) {
    if ($query->is_main_query() && is_home()) {
        $query->set('category_name','article');
    }
}

**Comment by pfefferle** [comment]
Perfect, nice workaround :)
