### ISSUE TITLE
Heading now populated with post number

### ISSUE THREAD

**Issue by davidmead** [pfefferle/SemPress#50]
Hi.

I've just updated to the latest version and it seems posts with a empty heading are now being populated with the post number. Is this right? It wasn't doing this before.

<img width="646" alt="screenshot 2017-05-10 20 20 36" src="https://cloud.githubusercontent.com/assets/1266930/25926668/704a1f76-35be-11e7-9faa-d98b6888d58a.png">

The code being inserted is...
`<a href="http://davidjohnmead.com/blog/2017/05/09/16088/" class="u-url url" title="Permalink to #16088" rel="bookmark" itemprop="url">#16088</a>`
...but when I go to edit the post the heading field is empty in Wordpress.

I don't remember a setting on the old version that stopped this. Am I missing something?

**Comment by pfefferle** [comment]
I added this because the empty titled caused some issues with feed readers and other systems. It is only generated for the output and not saved to the db, so it still shows an empty title in the edit mode. Can you explain to me, what you need/want to do, so I can give you better support.

**Comment by davidmead** [comment]
I was just used to it not having anything there.

I'll live with it for a while and see how I feel :-)

thx

**Comment by pfefferle** [comment]
so I would close it for now. feel free to re-open it, if you are aware of your feelings ;)
