### ISSUE TITLE
Content not pulling through when syndicating...

### ISSUE THREAD

**Issue by davidmead** [pfefferle/SemPress#52]
Hi Matthias.

Just written a [post on my site](http://davidjohnmead.com/blog/2017/05/14/16256/)...

<img width="568" alt="screenshot 2017-05-14 13 54 59" src="https://cloud.githubusercontent.com/assets/1266930/26036505/f154c904-38ac-11e7-82f7-eb26fe89de5f.png">

...but when it's syndicated, Twitter only displays [the post number (H1) and a link back to my blog](https://twitter.com/davidmead/status/863805260883775489). No content is pulling through.

<img width="614" alt="screenshot 2017-05-14 13 50 08" src="https://cloud.githubusercontent.com/assets/1266930/26036497/c6ece520-38ac-11e7-89f4-cca35f476745.png">

Where can I get the previous version of the theme so I can roll back?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/SemPress/issues/52" class="u-in-reply-to"></a>@davidmead I'm curious what method you're using for syndicating to twitter that's causing this? That may be the better question to address. It's likely if you're having a problem, others will as well.

In the interim, you can find all the prior releases here: https://github.com/pfefferle/SemPress/releases. From here you also have the ability to view the changes between releases so you can potentially easily track down the pieces of code which changed and may be causing issues.

You might also find it easier to create a [child theme](http://indieweb.org/WordPress/Themes#Child_Themes) of SemPress with some small changes to improve your specific issues, this way you'll still get other future updates from the parent.

**Comment by davidmead** [comment]
I'm currently using Bridgy Publish (v1.2.1) @chrisaldrich. Been working fine up to now.

Thanks for the links to the previous versions. I just want to rule it out, but I've had a lot of weirdness since updating. Good idea about the child theme.

**Comment by davidmead** [comment]
OK. So I'm not sure what's going on.

Rolling back to v1.5.6 gives me this [posting](https://twitter.com/davidmead/status/863905492552343552) to Twitter...
![image](https://cloud.githubusercontent.com/assets/1266930/26038905/9a3086e8-38e0-11e7-9af9-0ae63b558afc.png)
...going back further to v1.4 gives me this when [posting](https://twitter.com/davidmead/status/863907463007006721) to Twitter
![image](https://cloud.githubusercontent.com/assets/1266930/26038912/b57e4c14-38e0-11e7-9bd6-22d9861a1885.png)

Only thing I changed was the theme.

**Comment by pfefferle** [comment]
OK, it is because of the title... I think ownyourswarm uses the `p-name` if there is one, and after adding the post-id as headline, this seems to cause this problem.

**Comment by pfefferle** [comment]
but this is expected, thats why SemPress supports different post-types. An article always has a title and it makes sense to use the title, because the text might be too long for a tweet. `link`, `aside` and `note` does not have a title, because they are expected to be short.

**Comment by pfefferle** [comment]
@davidmead is this ok for you?

**Comment by davidmead** [comment]
I think so @pfefferle. Thx.
