### ISSUE TITLE
Image in gallery not respecting size

### ISSUE THREAD

**Issue by davidmead** [pfefferle/SemPress#53]
Hi @pfefferle, Me again.

I've noticed that all posts using the `[gallery size=full columns=1]` to display images, show them as very small. Swapping over to a random theme (Twenty Seventeen) the images now show at the proper size...full size and one column.

<img width="763" alt="screenshot 2017-05-25 22 05 21" src="https://cloud.githubusercontent.com/assets/1266930/26477972/39694326-4197-11e7-8d69-49e9654af231.png">
<img width="559" alt="screenshot 2017-05-25 22 08 48" src="https://cloud.githubusercontent.com/assets/1266930/26477973/3977a95c-4197-11e7-93e3-9003447064a0.png">

Is this something you're setting in SemPress?  This is the way that OwnYourGram has been inserting images into the post, so all images are now affected.

**Comment by pfefferle** [comment]
oh, valid point... will have a look!
