### ISSUE TITLE
home_url vs site_url for better security

### ISSUE THREAD

**Issue by mtomas7** [pfefferle/SemPress#54]
Hi, I'm implementing your new function to add schema.org for seach forms and I had this thought, wouldn't be better to use `home_url` vs `site_url`? Because you can wrap `home_url` in `esc_url` filter and get better security, but you cannot do this with `site_url`:

https://core.trac.wordpress.org/ticket/13051#comment:29

And I know, there is a difference betwean the site_url and home_url, but does it matter in the context of adding Schema.org support?

https://wordpress.stackexchange.com/questions/20294/whats-the-difference-between-home-url-and-site-url

Thank you!

**Comment by mtomas7** [comment]
On the same note, you are using these lines in header.php and footer.php:

`<meta itemprop="name" content="get_bloginfo( 'name', 'display' )" />
<meta itemprop="url" content="<?php echo home_url( '/' ); ?>" />`

First line should probably be:

`<meta itemprop="name" content="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" />`

And second line also could use esc_url:

<meta itemprop="url" content="<?php echo esc_url( home_url( '/' ) ); ?>" />

**Comment by pfefferle** [comment]
but `home_url` is not the same as `site_url` https://codex.wordpress.org/Function_Reference/site_url
