### ISSUE TITLE
Something wrong in the byline section I think...

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/SemPress#55]
If I install the theme the byline at the top of a post looks like this:

Posted on 30/06/2017 by <span class='p-author h-card'>Bill Bennett</span>

You can see this better on page at my staging site: https://billnz.mystagingwebsite.com

but I don't plan to keep that live for more than a week or so. 

I've hacked about inside the PHP and can't see why this would happen, but then I have beginner level PHP skills.

**Comment by pfefferle** [comment]
oh, you switched the theme to Independent Publisher... couldn't have a look before, sorry :(

do you use the microformats2 plugin? perhaps you can try to deactivate it, if you want to switch back to SemPress... otherwise, Independent Publisher is also a very good choice ;)

**Comment by billbennettnz** [comment]
Thanks for looking. I’ve switched back. It’s been an intense day… 

They are both good choices, I think I get the minimal, stripped-down look I’m after from SemPress. I’ve flicked the stageing site back to SemPress, because I think this may be something you need to look at anyway. 

The site is almost as I want it with SemPress, I just need to fix that line under the menu and centre the column. But you can see the problem under the headline with 

Posted on May 15, 2017 <https://billnz.mystagingwebsite.com/2017/05/15/ten-years-mail-pain-spark-yahoo/?customize_changeset_uuid=ca655803-5755-41b4-bd42-3114f359e432&customize_theme=sempress&customize_messenger_channel=preview-0> by <span class=‘p-author h-card'>billnz</span> <https://billnz.mystagingwebsite.com/author/billnz/?customize_changeset_uuid=ca655803-5755-41b4-bd42-3114f359e432&customize_theme=sempress&customize_messenger_channel=preview-0>

clearly if you look now. 

Bill Bennett
bill@billbennett.co.nz

+64 27508 2740

Read my website: billbennett.co.nz

**Comment by pfefferle** [comment]
OK, I think I found the problem... You have to disable the `wp-uf2` (Microformats2) plugin, because it adds tags, that are escaped by the theme... SemPress is fully microformats2 compatible so you really don't need it.

**Comment by billbennettnz** [comment]
Thanks, I'll check that tomorrow and report back.

**Comment by billbennettnz** [comment]
Thanks. That fixed it. Now I can plan to transfer the theme to my main site.

**Comment by billbennettnz** [comment]
Thank you Matthais. I’ve got the site running just the way I want it, not to get indiewebified. 



Bill Bennett
bill@billbennett.co.nz

+64 27508 2740

Read my website: billbennett.co.nz
