### ISSUE TITLE
How to have page numbers on category archive? 

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/SemPress#57]
I could probably fix this myself if I knew where to look, but I'm coming up empty.

**Comment by pfefferle** [comment]
can you make this a bit more concrete? where do you need the page numbers?

**Comment by billbennettnz** [comment]
It’s not necessary on the title of the first page of a category archive, but on the second and subsequent pages. So on my site the first page of the telecommunications category archive has the title “Telecommunications post archive” so does the second and subsequent pages. 

However if I got to the second page of the main site list, the title says “page 2 of 298”. 

This isn’t critical, but it causes Google Search Console to report archive pages as duplicates. Or at least it does this some of the time.

**Comment by pfefferle** [comment]
this is a core feature now
