### ISSUE TITLE
Cookies for Comments leaving image that messes up mf2

### ISSUE THREAD

**Issue by jgmac1106** [pfefferle/SemPress#60]
When trying to use Bridgy Publish to Twitter  we came across img alt='css.php' src="https://sempress.jgregorymcverry.com/wp-content/plugins/cookies-for-comments/css.php?k=7f2082cabf524557e729f13a3507d899&amp;o=i&amp;t=2036212725" width='1' height='1

The  1x1 px gif to set a cookie, gets inserted into the post content and mf2 thinks it's the post photo

Thanks to @sknebel for diagnostic help.

**Comment by pfefferle** [comment]
Isn't this a problem of the "cookies-for-comments" plugin?

**Comment by jgmac1106** [comment]
Yes it comes pre-installed on my shared host. https://community.reclaimhosting.com/t/mysterious-plugin/1654/2 Closing issue.
