### ISSUE TITLE
Add missing translations for nl-NL (Dutch)

### ISSUE THREAD

**Issue by metbril** [pfefferle/SemPress#66]
I added missing translations through

https://translate.wordpress.org/projects/wp-themes/sempress/nl/default

but am unsure how they will end up in this repo.

**Comment by pfefferle** [comment]
In review https://make.wordpress.org/polyglots/2018/10/04/pte-request-for-sempress-theme/

**Comment by pfefferle** [comment]
Done: https://make.wordpress.org/polyglots/2018/10/04/pte-request-for-sempress-theme/
