### ISSUE TITLE
Gutenberg compliancy

### ISSUE THREAD

**Issue by metbril** [pfefferle/SemPress#69]
I don't know the details of what's changing. But I'm curious if SemPress is Gutenberg compliant?

**Comment by pfefferle** [comment]
SemPress is Gutenberg compliant, but does not support all the features.

**Comment by pfefferle** [comment]
"does not support" means, that it does not show the options that are not supported (for example wide images: https://richtabor.com/gutenberg-image-alignments/)... nothing will break with SemPress and Gutenberg!
