### ISSUE TITLE
Strange addition to Twitter cross-post

### ISSUE THREAD

**Issue by vishae** [pfefferle/SemPress#70]
Recently changed over to SemPress but when I tried posting something on my website and using Bridgy plugin to cross post to Twitter, I see the following added to my Twitter post:

html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd …"

You can see the twitter post here: https://twitter.com/vishae/status/1030769594246619137

This only happens if I post whilst using the SemPress theme.
I'm not well versed enough in WP themes to figure out where the issue is coming from.

I'd originally posted this issue on the Bridgy GitHub (https://github.com/snarfed/wordpress-micropub/issues/154#issuecomment-415931521) because I thought it was related to the Bridgy plugin, but it seems to be related to the WP theme.

I'm hoping someone can help.

**Comment by pfefferle** [comment]
Sorry, this is no SemPress issue... I saw you changed the theme and it still hase the "W3C doctype" stuff in the HTML source code. Can you try to edit the post and switch to the HTML source? Perhaps you can remove it there.

**Comment by pfefferle** [comment]
It seems to be part of every of your posts, so it might be a plugin that adds the strange doctype.
