### ISSUE TITLE
Single Post - no Response info for Bookmark kind

### ISSUE THREAD

**Issue by vishae** [pfefferle/SemPress#72]
I notice that for post-kind bookmark, although the bookmarked information shows on the index page, it doesn’t show on single post. Is this a settings thing?

**Comment by dshanske** [comment]
Turn off the Jetpack sharing module. It seems to filter bookmarks out of content even if you aren't using it. Haven't figured out a way to fix it

**Comment by dshanske** [comment]
@pfefferle If you can help me figure out why the Jetpack Sharing Module is filtering out my additions to the_content, would be most appreciative though.

**Comment by vishae** [comment]
oh thanks so much, I was wondering whether I was going crazy.
