### ISSUE TITLE
Missing Page link for search results

### ISSUE THREAD

**Issue by bekoli** [pfefferle/SemPress#74]
Affected version: 1.5.12

Pages (Not Articles) are missing a link to a found page when listed in search result. 

Search results show only excerpt and there is no way to access the found page.

Due to this `url` is also missing for pages of search result when parsed for mf2:

```json
            "children": [
                {
                    "type": [
                        "h-entry"
                    ],
                    "properties": {
                        "name": [
                            "<redacted>"
                        ],
                        "summary": [
                            "<redacted>"
                        ]
                    },
                    "lang": "en-GB"
                }
            ]
```

**Comment by pfefferle** [comment]
Sorry, but I can not reproduce it. I tested it on your site and it seems to work: http://pin13.net/mf2/?url=https://beko.famkos.net/?s=eine

**Comment by bekoli** [comment]
Try http://pin13.net/mf2/?url=https://beko.famkos.net/?s=Umluftventilator

That pops a `Page` without `url` property.
