### ISSUE TITLE
Add p-category class to tags in post footer

### ISSUE THREAD

**Issue by metbril** [pfefferle/SemPress#76]
The indiewebify.me site suggests adding p-category tags to posts.

Should be set somewhere over here, I guess?

https://github.com/pfefferle/SemPress/blob/fbcb5232047b0c497710fd36bb44abf7cd028c5e/sempress/entry-footer.php#L26

I would try to submit a PR, but am not really comportable with how the templating system and functions work.

**Comment by metbril** [comment]
Perhaps changing this line will help:

https://github.com/pfefferle/SemPress/blob/fbcb5232047b0c497710fd36bb44abf7cd028c5e/sempress/entry-footer.php#L21

New code:

```php
$tag_list = get_the_tag_list( '<span class="p-category">', '</span>, <span class="p-category">', '</span>' );
```

(loses the translation)

**Comment by pfefferle** [comment]
Thanks for the issue and the code example! I implemented something similar for my Autonomie theme. I prepare a commit.
