### ISSUE TITLE
Inline CSS can't be overwritten

### ISSUE THREAD

**Issue by metbril** [pfefferle/SemPress#88]
I want to remove the shadows from the inline CSS and need to replace a function for that. 

When I simply copy and paste the original function `sempress_custom_css()` to my `functions.php`, my site shows an error and doesn't render. A completely empty function also errs.

When I change the function name (by adding `xxx` to the name, the site is rendered, so syntactically it should be OK.

The change is in a PR:

https://github.com/metbril/wordpress-sempress-child/pull/1/files

What am I missing here?

**Comment by metbril** [comment]
Critical error:

<img width="820" alt="Schermafbeelding 2022-02-01 om 22 13 56" src="https://user-images.githubusercontent.com/559346/152052473-ae6d39ea-853c-4a57-9b67-e10f1d027ab5.png">

**Comment by metbril** [comment]
I think I know what's wrong. The commit c6ffec09b1a4de67489d5db381f1429d4745f461 is not yet pushed to the WordPress directory.

**Comment by pfefferle** [comment]
Oh, sorry about that! I will prepare an update ASAP!

**Comment by pfefferle** [comment]
@metbril thanks for your work: https://themes.trac.wordpress.org/ticket/113300
