### ISSUE TITLE
Featured image to small for full width pages

### ISSUE THREAD

**Issue by metbril** [pfefferle/SemPress#90]
When using the full width page template (no sidebar), a featured image is only as wide as the regular content. It should be stretched to fit the full width of the page at 950 pixels.

Example: https://robertvanbregt.nl/nu/

![{402903B8-FFF2-4A4E-9530-424D7E06B482}](https://user-images.githubusercontent.com/559346/153032559-a430d3bb-7a3a-4d82-b5e0-57c4022fc9cb.png)

**Comment by pfefferle** [comment]
Have you uploaded the image before the change to full-width?

**Comment by metbril** [comment]
Yes. I used to use the small page width.

Workflow:
1. Upload image from computer to media library
2. Edit page and add featured image
3. Publish
4. Edit page and set page template to full width
5. Publish

**Comment by pfefferle** [comment]
Can you re-add the featured image and check if it works then?

**Comment by metbril** [comment]
I've tried without success. The image is 2500 pixels wide.

1. Edit page
2. Remove featured image
3. Publish page
4. Add featured image
5. Publish page
6. View page

![FD516460-6839-4ADE-90FC-60B25C887B79](https://user-images.githubusercontent.com/559346/153066861-16ebf977-d180-4d4d-a72c-a237447238c7.png)

**Comment by pfefferle** [comment]
Ok, that's not like expected, thanks for debugging!
